#!/bin/bash
echo "COMANDOS TMUX"
echo ""
echo "INICIAR INSTÂNCIA = Executar o comando tmux."
echo ""
echo "NOVA INSTÂNCIA	Ctrl+b+c"
echo "PAINEL LATERAL	Ctrl+b+\%"
echo "PAINEL ABAIXO	Ctrl+\""
echo "REDIMENSIONAR	Ctrl+b+setas"
echo "FECHAR		exit"
